[program:myflask]
# Afegir en  /etc/supervisor/conf.d/myflask.conf
# command=venv/bin/gunicorn --workers 3 --bind 127.0.0.1:5000 app:app
# directory=/var/www/html/myapp
# user=www-data
# environment=PATH="/var/www/html/myapp/venv/bin"
directory=/var/www/html/myapp
command=/var/www/html/myapp/bin/gunicorn --workers 2 --bind unix:/var/www/html/myapp/myflask.sock wsgi:app
user=www-data
autostart=true
autorestart=true
stdout_logfile=/var/www/html/myapp/gunicorn.log